
// Objective-C API for talking to the following Go packages
//
//	github.com/Hovelander/goAppleMusic/gobind/goAppleMusic
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GoAppleMusic_H__
#define __GoAppleMusic_H__

#include "GoGoAppleMusic.h"
#include "GoUniverse.h"

#endif
