// Objective-C API for talking to github.com/Hovelander/goAppleMusic/gobind/goAppleMusic Go package.
//   gobind -lang=objc -prefix=Go github.com/Hovelander/goAppleMusic/gobind/goAppleMusic
//
// File is generated by gobind. Do not edit.

#ifndef __GoGoAppleMusic_H__
#define __GoGoAppleMusic_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

FOUNDATION_EXPORT NSString* GoGoAppleMusicGreetings(NSString* name);

#endif
