// Objective-C API for talking to golang.org/x/mobile/example/bind/hello Go package.
//   gobind -lang=objc -prefix=Go golang.org/x/mobile/example/bind/hello
//
// File is generated by gobind. Do not edit.

#ifndef __GoHello_H__
#define __GoHello_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

FOUNDATION_EXPORT NSString* GoHelloGreetings(NSString* name);

#endif
