
// Objective-C API for talking to the following Go packages
//
//	golang.org/x/mobile/example/bind/hello
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Hello_H__
#define __Hello_H__

#include "GoHello.h"
#include "GoUniverse.h"

#endif
